---
version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.9.3
    volumes:
      - /docker/docker-compose/grafana_apps/loki:/etc/loki
    ports:
      - "3100:3100"
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - loki
    environment:
     - TZ=America/New_York

  promtail:
    image: grafana/promtail:2.9.10
    volumes:
      - /var/log:/var/log
      - /docker/docker-compose/grafana_apps/promtail:/etc/promtail
    ports:
      - "1514:1514"
    restart: unless-stopped
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - loki
    environment:
     - TZ=America/New_York

  grafana:
    image: grafana/grafana@sha256:1c2ca5868432ae258711afa5c18f8ae61a6c725bec2586b186e5cd0adbf31496
    volumes:
     - /docker/docker-compose/grafana_apps/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - loki
    environment:
     - TZ=America/New_York
