---
# version: "3.8"
version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.4.1
#   volumes:
#     - /docker/docker-compose/loki:/etc/loki
    ports:
      - "3100:3100"
    restart: unless-stopped
    command: -config.file=/etc/loki/local-config.yaml
#   command: -config.file=/etc/loki/loki-config.yml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.4.1
    volumes:
      - /var/log:/var/log
#     - /docker/docker-compose/promtail:/etc/promtail
#   ports:
#     - "1514:1514"
    restart: unless-stopped
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
#   user: "1000"
    volumes:
    - /docker/docker-compose/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - loki
